# Generated by Django 5.2.7 on 2026-05-09 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=50)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.society')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('flat_number', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('resident', 'Resident'), ('chairman', 'Chairman'), ('secretary', 'Secretary'), ('block_secretary', 'Block Secretary'), ('treasurer', 'Treasurer'), ('security', 'Security')], default='resident', max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.block')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.society')),
            ],
        ),
    ]
