# Generated by Django 5.2.7 on 2026-05-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='block',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='user',
            name='society',
        ),
        migrations.AddField(
            model_name='user',
            name='society_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='Society',
        ),
    ]
