# Generated by Django 6.1 on 2026-09-01 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_username', models.CharField(max_length=255)),
                ('a_email', models.CharField(max_length=255, unique=True)),
                ('a_password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenity_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('amenity_name', models.CharField(max_length=100)),
                ('amenity_location', models.CharField(max_length=100)),
                ('amenity_capacity', models.IntegerField()),
                ('amenity_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'amenity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(max_length=50)),
                ('asset_location', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
            ],
            options={
                'db_table': 'asset',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('block_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('block_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'blocks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CoreApiTemporaryotp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('otp_code', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'core_api_temporaryotp',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('bill_id', models.CharField(blank=True, max_length=6, null=True)),
                ('payment_type', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('poll_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('poll_title', models.CharField(max_length=150)),
                ('poll_description', models.TextField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'polls',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Societies',
            fields=[
                ('society_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('society_name', models.CharField(max_length=100)),
                ('society_address', models.TextField()),
                ('society_city', models.CharField(max_length=50)),
                ('society_pincode', models.CharField(max_length=10)),
                ('society_email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('society_phone', models.CharField(max_length=15)),
                ('standard_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('late_fee_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('billing_cycle', models.CharField(blank=True, max_length=20, null=True)),
                ('society_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'societies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitor_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_phone', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'visitor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('flat_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('flat_number', models.CharField(max_length=20)),
                ('floor_number', models.IntegerField()),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.blocks')),
            ],
            options={
                'db_table': 'flats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('receipt_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.payment')),
            ],
            options={
                'db_table': 'payment_receipt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PollsOption',
            fields=[
                ('option_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=100)),
                ('poll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.polls')),
            ],
            options={
                'db_table': 'polls_option',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('resident_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('move_in_date', models.DateField()),
                ('flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.flats')),
            ],
            options={
                'db_table': 'resident',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.resident'),
        ),
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('occupancy_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('occupancy_type', models.CharField(max_length=50)),
                ('is_primary', models.BooleanField(blank=True, null=True)),
                ('flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.flats')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.resident')),
            ],
            options={
                'db_table': 'occupancy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('nominee_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nominee_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.resident')),
            ],
            options={
                'db_table': 'nominee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('feedback_text', models.TextField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.resident')),
            ],
            options={
                'db_table': 'feedback',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, to='admin_panel.blocks')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.resident')),
            ],
            options={
                'db_table': 'complaint',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('maintenance_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('maintenance_date', models.DateField()),
                ('maintenance_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.asset')),
                ('recorded_by', models.ForeignKey(blank=True, db_column='recorded_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.resident')),
            ],
            options={
                'db_table': 'asset_maintenance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AmenityBooking',
            fields=[
                ('booking_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_deadline', models.DateTimeField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=5, null=True)),
                ('amenity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.amenity')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.resident')),
            ],
            options={
                'db_table': 'amenity_booking',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='blocks',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.societies'),
        ),
        migrations.AddField(
            model_name='asset',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.societies'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.societies'),
        ),
        migrations.CreateModel(
            name='SocietyExpenses',
            fields=[
                ('expense_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('expense_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.societies')),
            ],
            options={
                'db_table': 'society_expenses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SocietyFeatures',
            fields=[
                ('config_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('has_block_secretary', models.BooleanField(blank=True, null=True)),
                ('has_nominee', models.BooleanField(blank=True, null=True)),
                ('has_security', models.BooleanField(blank=True, null=True)),
                ('society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.societies')),
            ],
            options={
                'db_table': 'society_features',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=10, unique=True)),
                ('user_email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(blank=True, null=True)),
                ('is_staff', models.BooleanField(blank=True, null=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.roles')),
                ('society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.societies')),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('custom_maintenance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('move_in_date', models.DateField()),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.flats')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenant_owner_set', to='admin_panel.users')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.users')),
            ],
            options={
                'db_table': 'tenant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SocietyCommittee',
            fields=[
                ('committee_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('election_date', models.DateField()),
                ('term_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.roles')),
                ('society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.societies')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.users')),
            ],
            options={
                'db_table': 'society_committee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SecurityAlerts',
            fields=[
                ('alert_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, db_column='triggered_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.users')),
            ],
            options={
                'db_table': 'security_alerts',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='resident',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.users'),
        ),
        migrations.CreateModel(
            name='PollsResponse',
            fields=[
                ('response_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('voted_at', models.DateTimeField(blank=True, null=True)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.pollsoption')),
                ('poll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.polls')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.users')),
            ],
            options={
                'db_table': 'polls_response',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='polls',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.users'),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_SET_NULL, to='admin_panel.blocks')),
                ('society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.societies')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.users')),
            ],
            options={
                'db_table': 'notice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.UUIDField(primary_key=True, serialize=False)),
                ('message_text', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, related_name='messages_receiver_set', to='admin_panel.users')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.users')),
            ],
            options={
                'db_table': 'messages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('agenda', models.TextField()),
                ('meeting_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('minutes_doc', models.TextField(blank=True, null=True)),
                ('organized_by', models.ForeignKey(blank=True, db_column='organized_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.users')),
            ],
            options={
                'db_table': 'meeting',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceBill',
            fields=[
                ('bill_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('bill_month', models.CharField(max_length=20)),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.flats')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.users')),
            ],
            options={
                'db_table': 'maintenance_bill',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LostFoundItem',
            fields=[
                ('item_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('item_status', models.CharField(max_length=20)),
                ('item_location', models.CharField(max_length=100)),
                ('reported_date', models.DateField()),
                ('handled_by', models.ForeignKey(blank=True, db_column='handled_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lostfounditem_handled_by_set', to='admin_panel.users')),
                ('reported_by', models.ForeignKey(blank=True, db_column='reported_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.users')),
            ],
            options={
                'db_table': 'lost_found_item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CommitteeChange',
            fields=[
                ('request_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.roles')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='committeechange_admin_set', to='admin_panel.users')),
                ('requested_by', models.ForeignKey(blank=True, db_column='requested_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.users')),
                ('target_user', models.ForeignKey(blank=True, db_column='target_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='committeechange_target_user_set', to='admin_panel.users')),
            ],
            options={
                'db_table': 'committee_change',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('vehicle_allotment_number', models.CharField(max_length=50)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DB_CASCADE, to='admin_panel.resident')),
            ],
            options={
                'db_table': 'vehicle',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VisitorLogs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.CharField(max_length=200)),
                ('flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.flats')),
                ('recorded_by', models.ForeignKey(blank=True, db_column='recorded_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.users')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.visitor')),
            ],
            options={
                'db_table': 'visitor_logs',
                'managed': True,
            },
        ),
    ]
