# Generated by Django 6.0.6 on 2026-09-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenity_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('amenity_name', models.CharField(max_length=100)),
                ('amenity_location', models.CharField(max_length=100)),
                ('amenity_capacity', models.IntegerField()),
                ('amenity_status', models.CharField(default='available', max_length=20)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'db_table': 'amenity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AmenityBooking',
            fields=[
                ('booking_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('payment_deadline', models.DateTimeField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Amenity Booking',
                'verbose_name_plural': 'Amenity Bookings',
                'db_table': 'amenity_booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(max_length=50)),
                ('asset_location', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'db_table': 'asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('maintenance_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('maintenance_date', models.DateField()),
                ('maintenance_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorded_by', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'verbose_name': 'Asset Maintenance',
                'verbose_name_plural': 'Asset Maintenances',
                'db_table': 'asset_maintenance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('vehicle_allotment_number', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicle',
                'managed': False,
            },
        ),
    ]
