# Generated by Django 6.0.6 on 2026-06-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_username', models.CharField(max_length=255)),
                ('a_email', models.CharField(max_length=255, unique=True)),
                ('a_password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenity_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('amenity_name', models.CharField(max_length=100)),
                ('amenity_location', models.CharField(max_length=100)),
                ('amenity_capacity', models.IntegerField()),
                ('amenity_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'amenity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AmenityBooking',
            fields=[
                ('booking_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_deadline', models.DateTimeField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'amenity_booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(max_length=50)),
                ('asset_location', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
            ],
            options={
                'db_table': 'asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('maintenance_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('maintenance_date', models.DateField()),
                ('maintenance_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'asset_maintenance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('block_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('block_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'blocks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommitteeChange',
            fields=[
                ('request_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'committee_change',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'complaint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreApiTemporaryotp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('otp_code', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'core_api_temporaryotp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('flat_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('flat_number', models.CharField(max_length=20)),
                ('floor_number', models.IntegerField()),
            ],
            options={
                'db_table': 'flats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LostFoundItem',
            fields=[
                ('item_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('item_status', models.CharField(max_length=20)),
                ('item_location', models.CharField(max_length=100)),
                ('reported_date', models.DateField()),
            ],
            options={
                'db_table': 'lost_found_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceBill',
            fields=[
                ('bill_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('bill_month', models.CharField(max_length=20)),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'maintenance_bill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('agenda', models.TextField()),
                ('meeting_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('minutes_doc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meeting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.UUIDField(primary_key=True, serialize=False)),
                ('message_text', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('nominee_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nominee_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'nominee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('occupancy_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('occupancy_type', models.CharField(max_length=50)),
                ('is_primary', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'occupancy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('bill_id', models.CharField(blank=True, max_length=6, null=True)),
                ('payment_type', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('receipt_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_receipt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('poll_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('poll_title', models.CharField(max_length=150)),
                ('poll_description', models.TextField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'polls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PollsOption',
            fields=[
                ('option_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'polls_option',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PollsResponse',
            fields=[
                ('response_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('voted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'polls_response',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('resident_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('move_in_date', models.DateField()),
            ],
            options={
                'db_table': 'resident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityAlerts',
            fields=[
                ('alert_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'security_alerts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Societies',
            fields=[
                ('society_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('society_name', models.CharField(max_length=100)),
                ('society_address', models.TextField()),
                ('society_city', models.CharField(max_length=50)),
                ('society_pincode', models.CharField(max_length=10)),
                ('society_email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('society_phone', models.CharField(max_length=15)),
                ('standard_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('late_fee_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('billing_cycle', models.CharField(blank=True, max_length=20, null=True)),
                ('society_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'societies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocietyCommittee',
            fields=[
                ('committee_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('election_date', models.DateField()),
                ('term_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'society_committee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocietyExpenses',
            fields=[
                ('expense_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('expense_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'society_expenses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocietyFeatures',
            fields=[
                ('config_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('has_block_secretary', models.BooleanField(blank=True, null=True)),
                ('has_nominee', models.BooleanField(blank=True, null=True)),
                ('has_security', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'society_features',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('custom_maintenance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('move_in_date', models.DateField()),
                ('move_out_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tenant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=10, unique=True)),
                ('user_email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('vehicle_allotment_number', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitor_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_phone', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'visitor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisitorLogs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'visitor_logs',
                'managed': False,
            },
        ),
    ]
