# Generated by Django 6.0.6 on 2026-08-27 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceBill',
            fields=[
                ('bill_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('bill_month', models.CharField(max_length=20)),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Maintenance Bill',
                'verbose_name_plural': 'Maintenance Bills',
                'db_table': 'maintenance_bill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(default='MAINTENANCE', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='ONLINE', max_length=20)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('receipt_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Payment Receipt',
                'verbose_name_plural': 'Payment Receipts',
                'db_table': 'payment_receipt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocietyExpenses',
            fields=[
                ('expense_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('expense_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Society Expense',
                'verbose_name_plural': 'Society Expenses',
                'db_table': 'society_expenses',
                'managed': False,
            },
        ),
    ]
