# Generated by Django 6.0.6 on 2026-09-07 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAlerts',
            fields=[
                ('alert_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Security Alert',
                'verbose_name_plural': 'Security Alerts',
                'db_table': 'security_alerts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitor_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_phone', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'db_table': 'visitor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisitorLogs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Visitor Log',
                'verbose_name_plural': 'Visitor Logs',
                'db_table': 'visitor_logs',
                'managed': False,
            },
        ),
    ]
