# Generated by Django 6.0.6 on 2026-09-07 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeChange',
            fields=[
                ('request_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
            options={
                'verbose_name': 'Committee Change Request',
                'verbose_name_plural': 'Committee Change Requests',
                'db_table': 'committee_change',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LostFoundItem',
            fields=[
                ('item_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('item_status', models.CharField(max_length=20)),
                ('item_location', models.CharField(max_length=100)),
                ('reported_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Lost & Found Item',
                'verbose_name_plural': 'Lost & Found Items',
                'db_table': 'lost_found_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('agenda', models.TextField()),
                ('meeting_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('minutes_doc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'db_table': 'meeting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('poll_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('poll_title', models.CharField(max_length=150)),
                ('poll_description', models.TextField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='active', max_length=20)),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
                'db_table': 'polls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PollsOption',
            fields=[
                ('option_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Poll Option',
                'verbose_name_plural': 'Poll Options',
                'db_table': 'polls_option',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PollsResponse',
            fields=[
                ('response_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('voted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Poll Response',
                'verbose_name_plural': 'Poll Responses',
                'db_table': 'polls_response',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocietyCommittee',
            fields=[
                ('committee_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('election_date', models.DateField()),
                ('term_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
            options={
                'verbose_name': 'Society Committee Member',
                'verbose_name_plural': 'Society Committee Members',
                'db_table': 'society_committee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('custom_maintenance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('move_in_date', models.DateField()),
                ('move_out_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenant',
                'managed': False,
            },
        ),
    ]
