# Generated by Django 6.0.6 on 2026-08-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='MaintenanceBill',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentReceipt',
        ),
        migrations.DeleteModel(
            name='SocietyExpenses',
        ),
        migrations.AlterModelOptions(
            name='nominee',
            options={'managed': False, 'verbose_name': 'Nominee', 'verbose_name_plural': 'Nominees'},
        ),
    ]
