# Generated by Django 6.0.6 on 2026-09-07 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_delete_complaint_delete_maintenancebill_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.DeleteModel(
            name='AmenityBooking',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='AssetMaintenance',
        ),
        migrations.DeleteModel(
            name='CommitteeChange',
        ),
        migrations.DeleteModel(
            name='LostFoundItem',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.DeleteModel(
            name='Polls',
        ),
        migrations.DeleteModel(
            name='PollsOption',
        ),
        migrations.DeleteModel(
            name='PollsResponse',
        ),
        migrations.DeleteModel(
            name='SecurityAlerts',
        ),
        migrations.DeleteModel(
            name='SocietyCommittee',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
        migrations.DeleteModel(
            name='VisitorLogs',
        ),
    ]
